language: node_js
node_js:
  - "8"

sudo: required

services:
  - docker

script:
  - mkdir -p ~/.ssh
  - echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  - npm run build
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - npm run docker:build
  - npm run docker:push
  - scp ./docker-compose.yml root@${DEPLOYMENT_SERVER_IP}:~/
  - ssh root@$SERVER_IP "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}; docker pull dmitrydorofeev/tech-frontend; docker-compose up -d"

branches:
  only:
  - master
