version: '3'

services:
  frontend:
    image: dmitrydorofeev/tech-frontend
    ports:
      - 80:80
    links:
      - backend:backend
    volumes:
      - /tmp/letsencrypt/etc/live/jsdaddy.tech/:/etc/certs/
