version: '3'

services:
  frontend:
    image: dmitrydorofeev/tech-frontend
    ports:
      - 80:80
      - 443:443
    links:
      - backend:backend
    volumes:
      - "/tmp/letsencrypt/etc/:/etc/certs/"
