version: '3'

services:
  frontend:
    image: dmitrydorofeev/tech-frontend
    ports:
      - 80:80
    links:
      - backend:backend

  backend:
    image: dmitrydorofeev/tech-backend
    links:
      - mongo:mongo

  mongo:
    image: mongo
    volumes:
      - /data/db:/data/db
